services:
  ###> Application FrankenPHP ###
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-changeme}
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      MAILER_DSN: smtp://mailer:1025
      MAILER_FROM: noreply@doc2sail.local
    depends_on:
      - mailer
  ###< Application FrankenPHP ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###
